//
// Created by artsm on 24.05.2022.
//

#ifndef MVSHUGENUMBERCALCULATOR__DOUBLYLINKEDLIST_H
#define MVSHUGENUMBERCALCULATOR__DOUBLYLINKEDLIST_H

#endif //MVSHUGENUMBERCALCULATOR__DOUBLYLINKEDLIST_H
